server:
  port: ${PORT_EUREKA}

spring:
  application:
    name: eureka
  cloud:
    config:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never