server:
  port: 9090
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ##############
    password: ##############
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: ms-auth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  frontend-url: http://localhost:3000
  mail-from: onboarding@resend.dev