server:
  port: 8080

spring:
  cloud:
    config:
      enabled: false

    gateway:
      default-filters:
        - PreserveHostHeader

      routes:

        # USERS
        - id: ms-users
          uri: http://localhost:8090
          predicates:
            - Path=/api/users/**,/internal/auth/**

        # AUTH
        - id: ms-auth
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**

        # EQUIPMENT
        - id: ms-equipment
          uri: http://localhost:8091
          predicates:
            - Path=/api/equipments/**,/api/classifications/**,/api/equipments-area/**,/api/providers/**,/api/states/**,/api/locations/**

        # CMS - MEDIA
        - id: ms-cms
          uri: http://localhost:8082
          predicates:
            - Path=/api/media/**

        # INVENTORY
        - id: ms-inventory
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventories/**,/api/movements/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true