server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379

  cloud:
    config:
      enabled: false

    gateway:
      default-filters:
        - PreserveHostHeader

      routes:
        # 🔐 AUTH - LOGIN (con rate limit)
        - id: auth-login
          uri: http://localhost:9090
          predicates:
            - Path=/auth/login
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

        # 🔐 AUTH - FORGOT PASSWORD
        - id: auth-forgot
          uri: http://localhost:9090
          predicates:
            - Path=/auth/forgot-password
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
                key-resolver: "#{@ipKeyResolver}"

        # 🔐 AUTH - RESET PASSWORD
        - id: auth-reset
          uri: http://localhost:9090
          predicates:
            - Path=/auth/reset-password
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

        # AUTH GENERAL (sin rate limit)
        - id: ms-auth
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**

        # USERS
        - id: ms-users
          uri: http://localhost:8090
          predicates:
            - Path=/api/users/**,/internal/auth/**

        # EQUIPMENT
        - id: ms-equipment
          uri: http://localhost:8091
          predicates:
            - Path=/api/equipments/**,/api/classifications/**,/api/equipments-area/**,/api/providers/**,/api/states/**,/api/locations/**

        # CMS - MEDIA
        - id: ms-cms
          uri: http://localhost:8082
          predicates:
            - Path=/api/media/**

        # INVENTORY
        - id: ms-inventory
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventories/**,/api/movements/**

        # 🛠 MAINTENANCE
        - id: ms-maintenance
          uri: http://localhost:8084
          predicates:
            - Path=/api/maintenance/**

        # 📊 REPORTS & AUDIT
        - id: ms-reports-and-audit
          uri: http://localhost:8087
          predicates:
            - Path=/api/reports/**,/api/audit/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true