server:
  port: 8090
spring:
  cloud:
    config:
      enabled: false
  application:
    name: ms-users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop #         🔒  borra tablas en cada inicio
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # ✅ data.sql después del schema

  sql:
    init:
      mode: always           # ✅ Ejecuta data.sql SIEMPRE
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
