server:
  port: 8083

spring:
  application:
    name: ms-inventory

  cloud:
    config:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# 🔥 CONFIGURACIÓN FEIGN (IMPORTANTE)
feign:
  httpclient:
    enabled: true

# Feign — URL del Equipment MS
equipment-service:
  url: http://localhost:8091