server:
  port: 8091
spring:
  cloud:
    config:
      enabled: false
  application:
    name: equipment

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update                #borra tablas en cada inicio
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  #data.sql después del schema

  sql:
    init:
      mode: never #Ejecuta data.sql SIEMPRE

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 10
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka